### ISSUE TITLE
Evaluation stats

### ISSUE THREAD

**Issue by JRMeyer** [comodoro/deepspeech-cs#1]
Hi @comodoro , and thanks for open-sourcing your work!

It would be very helpful to list some evaluation info, such as WER or CER on whatever test data you have

**Comment by comodoro** [comment]
Thanks for the nudge! I plan to try to evaluate it eventually on some small
sets I have yet to create, in the meantime I will post current CV test
results.

po 12. 4. 2021 v 3:03 odesílatel Josh Meyer ***@***.***>
napsal:

**Comment by comodoro** [comment]
All releases contain metrics now
